server:
  port: 8086
spring:
  application:
    name: email-service
  rabbitmq:
    host: 192.168.23.129
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.23.129
    timeout: 50000ms