server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
      url: jdbc:mysql://localhost:3306/leyou
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  redis:
      host: 192.168.23.129
      timeout: 12000ms
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      ip-address: 127.0.0.1
      prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: E:\IdeaProjects\leyou\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
      appId: wx8397f8696b538317
      mchId: 1473426802
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
      connectTimeoutMs: 5000
      readTimeoutMs: 10000