server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
      url: jdbc:mysql://XXX/XXX
      username: XXX
      password: XXX
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  redis:
      host: XXX
      timeout: 12000ms
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      ip-address: 127.0.0.1
      prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: E:\IdeaProjects\leyou\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
      appId: XXX
      mchId: XXX
      key: XXX
      connectTimeoutMs: 5000
      readTimeoutMs: 10000
