server:
  port: 8010
spring:
  application:
    name: sms-service
  rabbitmq:
    host: XXXXX
    username: XXX
    password: XXX
    virtual-host: XXX
  redis:
    host: XXXX
    timeout: 12000ms
ly:
  sms:
    accessKeyId: xxxxx
    accessKeySecret:xxxx
    signName: 网站开发学习 # 签名名称
    verifyCodeTemplate: xxxx # 模板CODE
