server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加网关路由前缀
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    item-service: /item/**  # 添加网关路由映射
    search-service: /search/**  # 添加网关路由映射
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true # 添加host头信息，使返回的信息添加访问者的host，默认是false
  sensitive-headers:    # 忽略哪些敏感头信息,默认里面有"Cookie", "Set-Cookie", "Authorization"
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长：5s
ribbon:
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
ly:
  jwt:
    pubKeyPath: E:\IdeaProjects\leyou\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item