server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    //url: jdbc:mysql://81.68.243.227:33306/leyou
    username: root
    password: root
  rabbitmq:
    host: 192.168.23.129
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:  # 发送失败重试
        enabled: true
        initial-interval: 10000ms # 第一次发送失败重试时间
        max-interval: 30000ms # 发送失败重试时间不可超过max-interval
        multiplier: 2 # 第n次发送失败重试时间2n*initial-interval
      exchange: ly.item.exchange  # 发送消息默认走的交换机
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印输出sql语句